apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig-hardwareserviceorderservices
  namespace: {{ .Values.namespace}}
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://otel-collector.{{ .Values.namespace}}.svc.cluster.local:9411/api/v2/spans"