# Build and Deploy to Azure Kubernetes Service

trigger:
  branches:
    include:
    - trunk
  paths:
    include:
    - azure-pipelines-customers.yml
    - charts/customer-api
    - src/Core
    - src/Services/Customer

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '09ee8083-2a55-4731-876c-d6df7059bd8f'
  artifactsFeedSource: 'https://pkgs.dev.azure.com/mytos/OrigoV2/_packaging/Origo2/nuget/v3/index.json'
  imageRepository: 'customersbackend'
  containerRegistry: 'origov2acr.azurecr.io'
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    pullRequestKey: '$(System.PullRequest.PullRequestId)'
    pullRequestSourceBranch: '$(System.PullRequest.SourceBranch)'
  ${{ else }}:
    pullRequestKey: ''
    pullRequestSourceBranch: ''

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - template: general-build.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      dbContext: 'CustomerContext'
      dbProject: 'src/Services/Customer/CustomerServices/CustomerServices.csproj'
      migrationScriptOutputDir: '$(build.artifactstagingdirectory)/migrations'
      buildRepositoryLocalPath: '$(Build.Repository.LocalPath)'
      imageRepository: '$(imageRepository)'
      dockerfilePath: 'src/Services/Customer/Customer.API/Dockerfile'
      dockerRegistryServiceConnection: '09ee8083-2a55-4731-876c-d6df7059bd8f'
      buildId: '$(Build.BuildId)'
      sonarToken: '$(SonarToken)'
      artifactsFeedSource: 'https://pkgs.dev.azure.com/mytos/OrigoV2/_packaging/Origo2/nuget/v3/index.json'
      buildSourcesDirectory: $(Build.SourcesDirectory)
      chartName: 'customer-api'
      pullRequestKey: '$(pullRequestKey)'
      pullRequestSourceBranch: '$(pullRequestSourceBranch)'

- stage: DeployDev
  displayName: Deploy to Dev
  condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
  dependsOn: Build
  variables:
  - group: CustomerLibrary
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2AKS_Dev.develop'
      artifactDirectory: $(System.ArtifactsDirectory)
      dbConnection: '$(CustomerDbConnection)'
      releaseName: customerservices
      namespace: develop
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)

- stage: DeployTest
  displayName: Deploy to Test
  dependsOn: DeployDev
  variables:
  - group: CustomerLibrary
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2AKS.test'
      artifactDirectory: $(System.ArtifactsDirectory)
      dbConnection: '$(AssetsDbConnectionTest)'
      releaseName: customerservices
      namespace: test
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)

- stage: DeployProd
  displayName: Deploy to Prod
  dependsOn: DeployTest
  variables:
  - group: CustomerLibrary
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2AKS.prod'
      artifactDirectory: $(System.ArtifactsDirectory)
      dbConnection: '$(CustomerDbConnectionProd)'
      releaseName: customerservices
      namespace: prod
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)