# Build and Deploy to Azure Kubernetes Service using templates

trigger:
  branches:
    include:
    - trunk
  paths:
    include:
    - azure-pipelines-origoapigateway.yml
    - charts/origoapigateway
    - src/Core
    - src/ApiGateways

schedules:
- cron: "0 3 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - trunk

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '09ee8083-2a55-4731-876c-d6df7059bd8f'
  artifactsFeedSource: 'https://pkgs.dev.azure.com/mytos/OrigoV2/_packaging/Origo2/nuget/v3/index.json'
  imageRepository: 'origoapigateway'
  containerRegistry: 'origov2acr.azurecr.io'
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    pullRequestKey: '$(System.PullRequest.PullRequestId)'
    pullRequestSourceBranch: '$(System.PullRequest.SourceBranch)'
  ${{ else }}:
    pullRequestKey: ''
    pullRequestSourceBranch: ''

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - template: general-build.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      useDbMigrations: false
      buildRepositoryLocalPath: '$(Build.Repository.LocalPath)'
      imageRepository: '$(imageRepository)'
      dockerfilePath: 'src/ApiGateways/OrigoApiGateway/Dockerfile'
      dockerRegistryServiceConnection: '09ee8083-2a55-4731-876c-d6df7059bd8f'
      buildId: '$(Build.BuildId)'
      sonarToken: '$(SonarToken)'
      artifactsFeedSource: 'https://pkgs.dev.azure.com/mytos/OrigoV2/_packaging/Origo2/nuget/v3/index.json'
      buildSourcesDirectory: $(Build.SourcesDirectory)
      chartName: 'origoapigateway'
      pullRequestKey: '$(pullRequestKey)'
      pullRequestSourceBranch: '$(pullRequestSourceBranch)'

- stage: DeployDev
  displayName: Deploy to Dev
  condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
  dependsOn: Build
  variables:
  - group: OrigoApiGateway
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2AKS_Dev.develop'
      artifactDirectory: $(System.ArtifactsDirectory)
      releaseName: origoapigateway
      namespace: develop
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      helmOverrideDeployValues: ',ingress.hosts[0].host=origov2dev.mytos.no,ingress.hosts[0].paths[0]=/origoapi,ingress.tls[0].hosts[0]=origov2dev.mytos.no,ingress.tls[0].secretName=letsencrypt-origov2dev'
      runMigration: false
      generateReleaseNotes: true
      releaseDocName: 'Release_$(Build.BuildNumber).md'

- stage: DeployTest
  displayName: Deploy to Test
  dependsOn: DeployDev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
  variables:
  - group: OrigoApiGateway
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2Test.test'
      artifactDirectory: $(System.ArtifactsDirectory)
      releaseName: origoapigateway
      namespace: test
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      helmOverrideDeployValues: ',ingress.hosts[0].host=origov2test.mytos.no,ingress.hosts[0].paths[0]=/origoapi,ingress.tls[0].hosts[0]=origov2test.mytos.no,ingress.tls[0].secretName=letsencrypt-origov2dev'
      runMigration: false
      generateReleaseNotes: true
      releaseDocName: 'Release_$(Build.BuildNumber).md'

- stage: DeployProd
  displayName: Deploy to Prod
  dependsOn: DeployTest
  variables:
  - group: OrigoApiGateway
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2Prod.prod'
      artifactDirectory: $(System.ArtifactsDirectory)
      releaseName: origoapigateway
      namespace: prod
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      helmOverrideDeployValues: ',ingress.hosts[0].host=smart.techstep.io,ingress.hosts[0].paths[0]=/origoapi,ingress.tls[0].hosts[0]=smart.techstep.io,ingress.tls[0].secretName=letsencrypt-smart-techstepio'
      runMigration: false
      generateReleaseNotes: true
      releaseDocName: 'Release_$(Build.BuildNumber).md'

- stage: DeployScheduledTest
  displayName: Scheduled deploy to Test
  dependsOn: DeployDev
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Schedule'), eq(variables['e2esuccessful'], '1'), eq(variables['deployorigoapigatewaymicroservice'], '1'))
  variables:
  - group: OrigoApiGateway
  - group: Common
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2ScheduledTest.test'
      artifactDirectory: $(System.ArtifactsDirectory)
      releaseName: origoapigateway
      namespace: test
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      helmOverrideDeployValues: ',ingress.hosts[0].host=origov2test.mytos.no,ingress.hosts[0].paths[0]=/origoapi,ingress.tls[0].hosts[0]=origov2test.mytos.no,ingress.tls[0].secretName=letsencrypt-origov2dev'
      runMigration: false
      generateReleaseNotes: true
      releaseDocName: 'Release_$(Build.BuildNumber).md'

- stage: DeployScheduledProd
  displayName: Scheduled deploy to Prod
  dependsOn: DeployScheduledTest
  variables:
  - group: OrigoApiGateway
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2Prod.prod'
      artifactDirectory: $(System.ArtifactsDirectory)
      releaseName: origoapigateway
      namespace: prod
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      helmOverrideDeployValues: ',ingress.hosts[0].host=smart.techstep.io,ingress.hosts[0].paths[0]=/origoapi,ingress.tls[0].hosts[0]=smart.techstep.io,ingress.tls[0].secretName=letsencrypt-smart-techstepio'
      runMigration: false
      generateReleaseNotes: true
      releaseDocName: 'Release_$(Build.BuildNumber).md'
