# Deploy to Azure Kubernetes Service

trigger:
  branches:
    include:
    - main
    - release
    - develop
  paths:
    include:
    - azure-pipelines-origoapigateway.yml
    - charts/origoapigateway
    - src/ApiGateways

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '09ee8083-2a55-4731-876c-d6df7059bd8f'
  artifactsFeedSource: 'https://pkgs.dev.azure.com/mytos/OrigoV2/_packaging/Origo2/nuget/v3/index.json'
  imageRepository: 'origoapigateway'
  containerRegistry: 'origov2acr.azurecr.io'
  dockerfilePath: 'src/ApiGateways/OrigoApiGateway/Dockerfile'
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    namespace: prod
    tag: '$(Build.BuildId)_prod'
    hostname: smart.techstep.no
    environment: 'BackendServices.prod'
    letsencryptsecretname: 'letsencrypt-smart-techstepno'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'release') }}:
    namespace: test
    tag: '$(Build.BuildId)_test'
    hostname: origov2test.mytos.no
    environment: 'BackendServices.develop'
    letsencryptsecretname: 'letsencrypt-origov2dev'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'develop') }}:
    namespace: develop
    tag: '$(Build.BuildId)_develop'
    hostname: origov2dev.mytos.no
    environment: 'BackendServices.develop'
    letsencryptsecretname: 'letsencrypt-origov2dev'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
- stage: Build
  displayName: Build stage
  variables:
    - group: OrigoApiGateway
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NuGetAuthenticate@0
      displayName: Authenticating with internal NuGet package-feeds

    - task: Docker@2 # Can't use buildAndPush since arguments are needed
      displayName: Building Docker image
      inputs:
        command: build
        buildContext: '$(Build.Repository.LocalPath)'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        arguments: --build-arg SONAR_TOKEN=$(SonarToken) --build-arg BUILD_ID=$(Build.BuildId) --build-arg FEED_SOURCE=$(artifactsFeedSource) --build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Pushing Docker image to container registry
      inputs:
        command: push
        buildContext: '$(Build.Repository.LocalPath)'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - pwsh: |
        $id=docker images --filter "label=test=$(Build.BuildId)" -q | Select-Object -First 1
        docker create --name testcontainer $id
        docker cp testcontainer:/TestResults $(Build.SourcesDirectory)/TestResults
        docker cp testcontainer:/CodeCoverage $(Build.SourcesDirectory)/CodeCoverage
        docker rm testcontainer
      displayName: 'Copy test results' 

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/coverage.cobertura.xml'
      displayName: 'Publish code coverage'

    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
      displayName: 'Publish test results'

    - publish: charts/origoapigateway
      artifact: helmcharts

    - publish: src/ApiGateways/OrigoApiGateway/OrigoApiGateway.IntegrationTests
      artifact: postmanscripts

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  variables:
    - group: OrigoApiGateway
  jobs:
  - deployment: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: $(environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: HelmInstaller@0
            displayName: Install Helm
            inputs:
              helmVersion: 'latest'
              installKubectl: true

          - task: HelmDeploy@0
            displayName: Helm upgrade
            inputs:
              command: upgrade
              chartType: FilePath
              releaseName: origoapigateway
              namespace: $(namespace)
              overrideValues: "deployment.image.tag=$(tag),namespace=$(namespace),ingress.hosts[0].host=$(hostname),ingress.hosts[0].paths[0]=/origoapi,ingress.tls[0].hosts[0]=$(hostname),ingress.tls[0].secretName=$(letsencryptsecretname),deployment.probes.enabled=true"
              arguments: --version $(tag)
              chartPath: $(Pipeline.Workspace)/helmcharts
              install: true
          
          - task: Npm@0
            displayName: 'npm install newman'
            inputs:
              arguments: 'newman -g'
              cwd: '$(System.DefaultWorkingDirectory)'

          - task: Npm@0
            displayName: 'npm init'
            inputs:
              arguments: 'init -f'
              cwd: '$(System.DefaultWorkingDirectory)'

          - task: CmdLine@1
            displayName: 'Run newman'
            inputs:
              filename: newman
              arguments: 'run "$(Pipeline.Workspace)/postmanscripts/OrigoV2IntegrationTests.postman_collection.json" -e "$(Pipeline.Workspace)/postmanscripts/OrigoV2IntegrationTests-DevEnvironment.postman_environment.json" --disable-unicode'

  - deployment: DeployPullRequest
    displayName: Deploy Pull request
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
    pool:
      vmImage: $(vmImageName)
      
    environment: 'BackendServices.develop.$(k8sNamespaceForPR)'
    strategy:
      runOnce:
        deploy:
          steps:
          - reviewApp: develop

          - task: Kubernetes@1
            displayName: 'Create a new namespace for the pull request'
            inputs:
              command: apply
              useConfigurationFile: true
              inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'

          - task: HelmInstaller@0
            displayName: Install Helm
            inputs:
              helmVersion: 'latest'
              installKubectl: true

          - task: HelmDeploy@0
            displayName: Helm upgrade
            inputs:
              command: upgrade
              chartType: FilePath
              releaseName: Assets
              namespace: $(k8sNamespaceForPR)
              overrideValues: deployment.image.tag=$(tag),namespace=$(k8sNamespaceForPR),ingress.hosts.host=$(hostname),ingress.tls.hosts[0]=$(hostname)
              arguments: --version $(tag)
              chartPath: $(Pipeline.Workspace)/helmcharts/OrigoApiGateway
              install: true

          - task: Kubernetes@1
            name: get
            displayName: 'Get services in the new namespace'
            continueOnError: true
            inputs:
              command: get
              namespace: $(k8sNamespaceForPR)
              arguments: svc
              outputFormat: jsonpath='http://{.items[0].status.loadBalancer.ingress[0].ip}:{.items[0].spec.ports[0].port}'

          # Getting the IP of the deployed service and writing it to a variable for posing comment
          - script: |
              url="$(get.KubectlOutput)"
              message="Your review app has been deployed"
              if [ ! -z "$url" -a "$url" != "http://:" ] 
              then
                message="${message} and is available at $url.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app."
              fi
              echo "##vso[task.setvariable variable=GITHUB_COMMENT]$message"