# Build and Deploy to Azure Kubernetes Service

trigger:
  branches:
    include:
    - trunk
  paths:
    include:
    - azure-pipelines-subscriptionmanagement.yml
    - src/Core
    - charts/subscriptionmanagement-api
    - src/Services/subscriptionmanagement

schedules:
- cron: "0 3 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - trunk

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '09ee8083-2a55-4731-876c-d6df7059bd8f'
  artifactsFeedSource: 'https://pkgs.dev.azure.com/mytos/OrigoV2/_packaging/Origo2/nuget/v3/index.json'
  imageRepository: 'subscriptionmanagement'
  containerRegistry: 'origov2acr.azurecr.io'
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    pullRequestKey: '$(System.PullRequest.PullRequestId)'
    pullRequestSourceBranch: '$(System.PullRequest.SourceBranch)'
  ${{ else }}:
    pullRequestKey: ''
    pullRequestSourceBranch: ''

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - template: general-build.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      dbContext: 'SubscriptionManagementContext'
      dbProject: 'src/Services/SubscriptionManagement/SubscriptionManagementServices/SubscriptionManagementServices.csproj'
      migrationScriptOutputDir: '$(build.artifactstagingdirectory)/migrations'
      buildRepositoryLocalPath: '$(Build.Repository.LocalPath)'
      imageRepository: '$(imageRepository)'
      dockerfilePath: 'src/Services/SubscriptionManagement/SubscriptionManagement.API/Dockerfile'
      dockerRegistryServiceConnection: '09ee8083-2a55-4731-876c-d6df7059bd8f'
      buildId: '$(Build.BuildId)'
      sonarToken: '$(SonarToken)'
      artifactsFeedSource: 'https://pkgs.dev.azure.com/mytos/OrigoV2/_packaging/Origo2/nuget/v3/index.json'
      buildSourcesDirectory: $(Build.SourcesDirectory)
      chartName: 'subscriptionmanagement-api'
      pullRequestKey: '$(pullRequestKey)'
      pullRequestSourceBranch: '$(pullRequestSourceBranch)'

- stage: DeployDev
  displayName: Deploy to Dev
  condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
  dependsOn: Build
  variables:
  - group: SubscriptionManagementLibrary
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2AKS_Dev.develop'
      artifactDirectory: $(System.ArtifactsDirectory)
      dbConnection: '$(SubscriptionmanagementDbConnection)'
      releaseName: subscriptionmanagementservices
      namespace: develop
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      generateReleaseNotes: true

- stage: DeployTest
  displayName: Deploy to Test
  dependsOn: DeployDev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
  variables:
  - group: SubscriptionManagementLibrary
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2Test.test'
      artifactDirectory: $(System.ArtifactsDirectory)
      dbConnection: '$(SubscriptionmanagementDbConnectionTest)'
      releaseName: subscriptionmanagementservices
      namespace: test
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      generateReleaseNotes: true

- stage: DeployProd
  displayName: Deploy to Prod
  dependsOn: DeployTest
  variables:
  - group: SubscriptionManagementLibrary
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2Prod.prod'
      artifactDirectory: $(System.ArtifactsDirectory)
      dbConnection: '$(SubscriptionmanagementDbConnectionProd)'
      releaseName: subscriptionmanagementservices
      namespace: prod
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      generateReleaseNotes: true

- stage: DeployScheduledTest
  displayName: Scheduled deploy to Test
  dependsOn: DeployDev
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Schedule'), eq(variables['e2esuccessful'], '1'), eq(variables['deploysubscriptionmanagementmicroservice'], '1'))
  variables:
  - group: SubscriptionManagementLibrary
  - group: Common
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2ScheduledTest.test'
      artifactDirectory: $(System.ArtifactsDirectory)
      dbConnection: '$(SubscriptionmanagementDbConnectionTest)'
      releaseName: subscriptionmanagementservices
      namespace: test
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      generateReleaseNotes: true

- stage: DeployScheduledProd
  displayName: Scheduled deploy to Prod
  dependsOn: DeployScheduledTest
  variables:
  - group: SubscriptionManagementLibrary
  jobs:
  - template: general-deploy.yaml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'OrigoV2Prod.prod'
      artifactDirectory: $(System.ArtifactsDirectory)
      dbConnection: '$(SubscriptionmanagementDbConnectionProd)'
      releaseName: subscriptionmanagementservices
      namespace: prod
      tag: '$(Build.BuildId)'
      pipelineWorkspace: $(Pipeline.Workspace)
      generateReleaseNotes: true
