apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: user_pub_sub
  namespace: {{ .Values.namespace}}
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://rabittmq-rabbitmq.{{ .Values.namespace}}.svc"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel
scopes:
  - customerservices
  - subscriptionmanagementservices