# Template for deploying a backend microservice

parameters:
- name: vmImage
  default: 'ubuntu-latest'
- name: environment
  default: 'OrigoV2AKS_Dev.develop'
- name: artifactDirectory
  default: ''
- name: dbConnection
  default: ''
- name: runMigration
  type: boolean
  default: true
- name: useLoggingDb
  type: boolean
  default: true
- name: releaseName
  default: ''
- name: namespace
  default: 'develop'
- name: tag
  default: ''
- name: pipelineWorkspace
  default: ''
- name: helmOverrideDeployValues
  default: ''
- name: generateReleaseNotes
  type: boolean
  default: false


jobs:
- ${{ if eq(parameters.runMigration, true) }}:
  - deployment: MigrateDatabase
    environment: ${{ parameters.environment }}
    displayName: Migrate database
    pool:
      vmImage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download migration scripts
            inputs:
              artifactName: 'migrations'
              downloadPath: '${{ parameters.artifactDirectory }}/migrations'
          - task: SqlAzureDacpacDeployment@1
            displayName: Run sql migrations
            inputs:
              azureConnectionType: ConnectedServiceNameARM
              azureSubscription: OrigoV2ServiceConnection
              authenticationType: connectionString
              connectionString: ${{ parameters.dbConnection }}
              deployType: SqlTask
              sqlFile: '${{ parameters.artifactDirectory }}/migrations/migrations.sql'
          - ${{ if eq(parameters.useLoggingDb, true) }}:
            - task: SqlAzureDacpacDeployment@1
              displayName: Run logging sql migrations
              inputs:
                azureConnectionType: ConnectedServiceNameARM
                azureSubscription: OrigoV2ServiceConnection
                authenticationType: connectionString
                connectionString: ${{ parameters.dbConnection }}
                deployType: SqlTask
                sqlFile: '${{ parameters.artifactDirectory }}/migrations/logging_migrations.sql'
  
- deployment: Deploy
  displayName: Deploy
  pool:
    vmImage: ${{ parameters.vmImage }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - ${{ if eq(parameters.GenerateReleaseNotes, true) }}:
            # Generate Release Notes (Crossplatform)
            # Description - Generates a release notes file in a format of your choice from the build or release history
            - task: XplatGenerateReleaseNotes@3
              displayName: 'Generate release notes'
              inputs: 
                 # Required arguments
                 outputfile: $(System.DefaultWorkingDirectory)\releasenotes.md
                 templateLocation: InLine
                 templatefile: 
                 inlinetemplate: |
                    # Notes for release  {{releaseDetails.releaseDefinition.name}}    
                    **Build Number**: {{buildDetails.id}}
                    **Compared Release Number**  : {{compareReleaseDetails.name}}    
                    **Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}} 

                    # Associated Pull Requests ({{pullRequests.length}})
                    {{#forEach pullRequests}}
                    {{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
                    *  **{{this.pullRequestId}}** {{this.title}}
                    {{/forEach}}

                    # Builds with associated WI/CS ({{builds.length}})
                    {{#forEach builds}}
                    {{#if isFirst}}## Builds {{/if}}
                    -  Build {{this.build.buildNumber}}
                    {{#forEach this.commits}}
                       - CS {{this.id}}
                          - **Message:** {{this.message}}
                    {{/forEach}}
                    {{#forEach this.workitems}}
                       - WI {{this.id}}
                          - **Title** {{lookup this.fields 'System.Title'}}
                    {{/forEach}} 
                    {{#forEach this.tests}}
                       - Test {{this.id}} 
                          -  **Name** {{this.testCase.name}}
                          -  **Outcome** {{this.outcome}}
                    {{/forEach}} 
                    {{/forEach}}

                    # Global list of WI ({{workItems.length}})
                    {{#forEach workItems}}
                    {{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
                    *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
                       - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
                       - **Tags** {{lookup this.fields 'System.Tags'}}
                       - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
                    {{/forEach}}

                    # Global list of WI with parents and children
                    {{#forEach this.workItems}}
                    {{#if isFirst}}### WorkItems {{/if}}
                    *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
                       - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
                       - **Tags** {{lookup this.fields 'System.Tags'}}
                       - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
                       - **Description** {{{lookup this.fields 'System.Description'}}}
                       - **Parents**
                    {{#forEach this.relations}}
                    {{#if (contains this.attributes.name 'Parent')}}
                    {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
                          - {{this.id}} - {{lookup this.fields 'System.Title'}} 
                    {{/with}}
                    {{/if}}
                    {{/forEach}} 
                       - **Children**
                    {{#forEach this.relations}}
                    {{#if (contains this.attributes.name 'Child')}}
                    {{#with (lookup_a_work_item ../../relatedWorkItems  this.url)}}
                          - {{this.id}} - {{lookup this.fields 'System.Title'}} 
                    {{/with}}
                    {{/if}}
                    {{/forEach}} 
                    {{/forEach}} 

                    # WI with 'Tag 1'
                    {{#forEach this.workItems}}
                    {{#if isFirst}}### WorkItems with 'Tag 1'{{/if}}
                    {{#if (contains (lookup this.fields 'System.Tags') 'Tag 1')}}
                    *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
                       - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
                       - **Tags** {{lookup this.fields 'System.Tags'}}
                    {{/if}}
                    {{/forEach}} 

                    # WI with 'Tag 1' or 'TAG1'
                    {{#forEach this.workItems}}
                    {{#if isFirst}}### WorkItems with 'Tag 1' or 'TAG2'{{/if}}
                    {{#if (or (contains (lookup this.fields 'System.Tags') 'Tag 1') (contains (lookup this.fields 'System.Tags') 'TAG2'))}}
                    *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
                       - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
                       - **Tags** {{lookup this.fields 'System.Tags'}}
                    {{/if}}
                    {{/forEach}} 

                    # WI with 'Tag 1' and 'TAG1'
                    {{#forEach this.workItems}}
                    {{#if isFirst}}### WorkItems with 'Tag 1' and 'TAG2'{{/if}}
                    {{#if (and (contains (lookup this.fields 'System.Tags') 'Tag 1') (contains (lookup this.fields 'System.Tags') 'TAG2'))}}
                    *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
                       - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
                       - **Tags** {{lookup this.fields 'System.Tags'}}
                    {{/if}}
                    {{/forEach}} 

                    # Global list of CS ({{commits.length}})
                    {{#forEach commits}}
                    {{#if isFirst}}### Associated commits{{/if}}
                    * ** ID{{this.id}}** 
                       -  **Message:** {{this.message}}
                       -  **Commited by:** {{this.author.displayName}} 
                       -  **FileCount:** {{this.changes.length}} 
                    {{#forEach this.changes}}
                          -  **File path (TFVC or TfsGit):** {{this.item.path}}  
                          -  **File filename (GitHub):** {{this.filename}}  
                    {{/forEach}}
                    {{/forEach}}

                    # Global list of test ({{tests.length}})
                    {{#forEach tests}}
                    {{#if isFirst}}### Tests {{/if}}
                    * ** ID{{this.id}}** 
                       -  Name: {{this.testCase.name}}
                       -  Outcome: {{this.outcome}}
                    {{/forEach}}
                 dumpPayloadToConsole: true
                 dumpPayloadToFile: false
                 replaceFile: True
                 appendToFile: True
                 getParentsAndChildren: False
                 getAllParents: False
                 getIndirectPullRequests: False
                 stopOnError: False
                 considerPartiallySuccessfulReleases: False
                 checkForManuallyLinkedWI: true
                 wiqlFromTarget: WorkItems

            # Git based WIKI Single File Updater from Black Marble
            # Description - A tools to update or create a file in a WIKI based in a Git repo
            - task: WikiUpdaterTask@1
              inputs:
                 # Required arguments
                 repo: dev.azure.com/mytos/OrigoV2/_git/OrigoV2.wiki
                 filename: $(System.DefaultWorkingDirectory)\releasenotes.md
                 replaceFile: false
                 appendToFile: True
                 contents: 
                 sourceFile: 
                 message: 
                 gitname: 
                 gitemail: 
                 localpath: $(System.DefaultWorkingDirectory)\repo
                 useAgentToken: true

        - task: HelmInstaller@0
          displayName: Install Helm
          inputs:
            helmVersion: 'latest'
            installKubectl: true

        - task: HelmDeploy@0
          displayName: Helm upgrade
          inputs:
            command: upgrade
            chartType: FilePath
            releaseName: ${{ parameters.releaseName }}
            namespace: ${{ parameters.namespace }}
            overrideValues: "deployment.image.tag=${{ parameters.tag }},namespace=${{ parameters.namespace }},deployment.probes.enabled=true${{ parameters.helmOverrideDeployValues }}"
            arguments: --version ${{ parameters.tag }}
            chartPath: ${{ parameters.pipelineWorkspace }}/helmcharts
            install: true