# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: origodomainservices

extensions:
  - name: dapr
    enable-profiling: true
    log-level: debug
  - name: zipkin

services:
  - name: assetservices
    project: src/Services/Asset/Asset.API/Asset.API.csproj
    bindings:
    - port: 58888
  - name: customerservices
    project: src/Services/Customer/Customer.API/Customer.API.csproj
    bindings:
    - port: 58889
  - name: origoapigateway
    project: src/ApiGateways/OrigoApiGateway/OrigoApiGateway/OrigoApiGateway.csproj
    bindings:
    - port: 58890
  - name: productcatalogservices
    project: src/Services/ProductCatalog/ProductCatalog.API/ProductCatalog.API.csproj
    bindings:
    - port: 58891
  - name: subscriptionmanagementservices
    project: src/Services/SubscriptionManagement/SubscriptionManagement.API/SubscriptionManagement.API.csproj
    bindings:
    - port: 58892
  - name: hardwareserviceorderservices
    project: src/Services/HardwareServiceOrder/HardwareServiceOrder.API/HardwareServiceOrder.API.csproj
    bindings:
    - port: 58893
  - name: customerdatasyncapi
    project: ../CustomerDataSync/src/CustomerDataSync.csproj
    bindings:
    - port: 58894
  - name: rabbit
    image: rabbitmq:3-management
    bindings:
    - name: amqp
      protocol: amqp
      port: 5672