// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalog.Infrastructure.Infrastructure.Context;

#nullable disable

namespace ProductCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(ProductCatalogContext))]
    [Migration("20221011121049_new_seed_product_permission")]
    partial class new_seed_product_permission
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FeatureCatalog.Infrastructure.Models.Database.Joins.FeatureExcludes", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasComment("The feature that has exclusions");

                    b.Property<int>("ExcludesFeatureId")
                        .HasColumnType("int")
                        .HasColumnOrder(1)
                        .HasComment("The 'FeatureID' cant be combined or used with this feature. This is a one-way requirement");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("FeatureId", "ExcludesFeatureId");

                    b.HasIndex("ExcludesFeatureId");

                    b.ToTable("FeatureExcludes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("FeatureCatalog.Infrastructure.Models.Database.Joins.FeatureRequiresAll", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasComment("The feature that has requirements");

                    b.Property<int>("RequiresFeatureId")
                        .HasColumnType("int")
                        .HasColumnOrder(1)
                        .HasComment("The 'FeatureID' requires all these features before it can be added or used. This is a one-way requirement");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("FeatureId", "RequiresFeatureId");

                    b.HasIndex("RequiresFeatureId");

                    b.ToTable("FeatureRequiresAll");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("FeatureCatalog.Infrastructure.Models.Database.Joins.FeatureRequiresOne", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasComment("The feature that has a requirement");

                    b.Property<int>("RequiresFeatureId")
                        .HasColumnType("int")
                        .HasColumnOrder(1)
                        .HasComment("The 'FeatureID' requires one of these features before it can be added or used. This is a one-way requirement");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("FeatureId", "RequiresFeatureId");

                    b.HasIndex("RequiresFeatureId");

                    b.ToTable("FeatureRequiresOne");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccessControlPermissionNode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(2)
                        .HasComment("A fixed and unique access-control node-name that's used by the front- and back-end to enable or disable functionality for an organization. The node-name must consist of only characters, formated in PascalCase. Example: 'MyPermissionNodeIdentifier'");

                    b.Property<int>("FeatureTypeId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("Id");

                    b.HasAlternateKey("AccessControlPermissionNode");

                    b.HasIndex("FeatureTypeId");

                    b.ToTable("Features");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessControlPermissionNode = "BasicUserManagement",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            AccessControlPermissionNode = "BasicAssetManagement",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 14,
                            AccessControlPermissionNode = "SubscriptionManagement",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 15,
                            AccessControlPermissionNode = "AssetBookValue",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 16,
                            AccessControlPermissionNode = "InternalAssetReturn",
                            FeatureTypeId = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 7,
                            AccessControlPermissionNode = "RecycleAndWipeAssetReturn",
                            FeatureTypeId = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 8,
                            AccessControlPermissionNode = "BasicHardwareRepair",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 9,
                            AccessControlPermissionNode = "EmployeeAccess",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 10,
                            AccessControlPermissionNode = "DepartmentStructure",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 11,
                            AccessControlPermissionNode = "OnAndOffboarding",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 12,
                            AccessControlPermissionNode = "BuyoutAsset",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 13,
                            AccessControlPermissionNode = "AssetManagement",
                            FeatureTypeId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.FeatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("Id");

                    b.ToTable("FeatureTypes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Joins.ProductExcludes", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasComment("The product that has exclusions");

                    b.Property<int>("ExcludesProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(1)
                        .HasComment("The 'ProductId' cant be combined or used with this product. This is a one-way requirement");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("ProductId", "ExcludesProductId");

                    b.HasIndex("ExcludesProductId");

                    b.ToTable("ProductExcludes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Joins.ProductFeature", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("FeatureId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeatures");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));

                    b.HasData(
                        new
                        {
                            FeatureId = 14,
                            ProductId = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 1,
                            ProductId = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 2,
                            ProductId = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 9,
                            ProductId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 10,
                            ProductId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 11,
                            ProductId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 13,
                            ProductId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 12,
                            ProductId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 8,
                            ProductId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 15,
                            ProductId = 4,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            FeatureId = 7,
                            ProductId = 5,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Joins.ProductRequiresAll", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RequiresProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("ProductId", "RequiresProductId");

                    b.HasIndex("RequiresProductId");

                    b.ToTable("ProductRequiresAll");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Joins.ProductRequiresOne", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RequiresProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("ProductId", "RequiresProductId");

                    b.HasIndex("RequiresProductId");

                    b.ToTable("ProductRequiresOne");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));

                    b.HasData(
                        new
                        {
                            ProductId = 5,
                            RequiresProductId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("Id");

                    b.HasAlternateKey("ExternalId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1)
                        .HasComment("The partner that owns and sells this product");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PartnerId = new Guid("5741b4a1-4eef-4fc2-b1b8-0ba7f41ed93c"),
                            ProductTypeId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            PartnerId = new Guid("5741b4a1-4eef-4fc2-b1b8-0ba7f41ed93c"),
                            ProductTypeId = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            PartnerId = new Guid("5741b4a1-4eef-4fc2-b1b8-0ba7f41ed93c"),
                            ProductTypeId = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            PartnerId = new Guid("5741b4a1-4eef-4fc2-b1b8-0ba7f41ed93c"),
                            ProductTypeId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            PartnerId = new Guid("5741b4a1-4eef-4fc2-b1b8-0ba7f41ed93c"),
                            ProductTypeId = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The ID of the user that performed the last update.");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("FeatureCatalog.Infrastructure.Models.Database.Joins.FeatureExcludes", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Feature", "RequiresFeature")
                        .WithMany("HasExcludesDependenciesFrom")
                        .HasForeignKey("ExcludesFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Feature", "Feature")
                        .WithMany("Excludes")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("RequiresFeature");
                });

            modelBuilder.Entity("FeatureCatalog.Infrastructure.Models.Database.Joins.FeatureRequiresAll", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Feature", "Feature")
                        .WithMany("RequiresAll")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Feature", "RequiresFeature")
                        .WithMany("HasRequiresAllDependenciesFrom")
                        .HasForeignKey("RequiresFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("RequiresFeature");
                });

            modelBuilder.Entity("FeatureCatalog.Infrastructure.Models.Database.Joins.FeatureRequiresOne", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Feature", "Feature")
                        .WithMany("RequiresOne")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Feature", "RequiresFeature")
                        .WithMany("HasRequiresOneDependenciesFrom")
                        .HasForeignKey("RequiresFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("RequiresFeature");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Feature", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.FeatureType", "Type")
                        .WithMany("Features")
                        .HasForeignKey("FeatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ProductCatalog.Infrastructure.Models.Database.FeatureTranslation", "Translations", b1 =>
                        {
                            b1.Property<int>("FeatureId")
                                .HasColumnType("int")
                                .HasColumnOrder(0);

                            b1.Property<string>("Language")
                                .HasMaxLength(2)
                                .IsUnicode(false)
                                .HasColumnType("char(2)")
                                .HasColumnOrder(1)
                                .IsFixedLength()
                                .HasComment("The language for this translation. This should be stored in lowercase 'ISO 639-1' format");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnOrder(3)
                                .HasComment("An optional description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnOrder(2)
                                .HasComment("A short, descriptive name");

                            b1.Property<DateTime>("PeriodEnd")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTime>("PeriodStart")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodStart");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uniqueidentifier")
                                .HasComment("The ID of the user that performed the last update.");

                            b1.HasKey("FeatureId", "Language");

                            b1.ToTable("FeatureTranslation");

                            b1.ToTable(tb => tb.IsTemporal(ttb =>
                                {
                                    ttb
                                        .HasPeriodStart("PeriodStart")
                                        .HasColumnName("PeriodStart");
                                    ttb
                                        .HasPeriodEnd("PeriodEnd")
                                        .HasColumnName("PeriodEnd");
                                }
                            ));

                            b1.WithOwner()
                                .HasForeignKey("FeatureId");

                            b1.HasData(
                                new
                                {
                                    FeatureId = 1,
                                    Language = "en",
                                    Description = "Allows organizations to perform the basic user management tasks. This is an extension of the options that's available for all organizations.",
                                    Name = "Basic User Management",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 1,
                                    Language = "nb",
                                    Description = "Lar en organisasjon utføre grunnleggende brukerbehandling. Dette er en utvidelse av funksjonaliteten som er tilgjengelig for alle organisasjoner.",
                                    Name = "Grunnleggende brukerhåndtering",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 2,
                                    Language = "en",
                                    Description = "Allows organizations to perform the basic user management tasks.",
                                    Name = "Basic Asset Management",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 2,
                                    Language = "nb",
                                    Description = "Lar en organisasjon utføre grunnleggende behandling av assets.",
                                    Name = "Grunnleggende asset-håndtering",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 14,
                                    Language = "en",
                                    Description = "Allows organizations to perform subscription management tasks.",
                                    Name = "Subscription Management",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 14,
                                    Language = "nb",
                                    Description = "Gir kunder tilgang til administrering av abonnementer.",
                                    Name = "Abonnent håndtering",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 15,
                                    Language = "en",
                                    Description = "Allows organizations to book value and purchase price related tasks.",
                                    Name = "Asset Book Value",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 15,
                                    Language = "nb",
                                    Description = "Gir organisasjonen mulighet til å utføre oppgaver relatert til bokført verdi og kjøpspris",
                                    Name = "Håndtering av bokført verdi",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 16,
                                    Language = "en",
                                    Description = "The organization handles the return of assets internally.",
                                    Name = "Internal Asset Return",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 16,
                                    Language = "nb",
                                    Description = "Organisasjonen håndterer return av asset internt.",
                                    Name = "Intern asset retur",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 7,
                                    Language = "en",
                                    Description = "Makes it possible to return supported assets through 'Recycle & Wipe' service-orders.",
                                    Name = "Recycle & Wipe asset return",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 7,
                                    Language = "nb",
                                    Description = "Gjør det mulig å returnere støttede enheter via 'Recycle & Wipe' service-ordrer.",
                                    Name = "Recycle & Wipe asset retur",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 8,
                                    Language = "en",
                                    Description = "Makes it possible for organizations to create ordinary repair/service-orders on supported hardware assets.",
                                    Name = "Basic Hardware Repair",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 8,
                                    Language = "nb",
                                    Description = "Gjør det mulig for organisasjoner å opprette ordinære reparasjon/service-ordrer på støttede hardware assets.",
                                    Name = "Grunnlegende Hardware Reparasjon",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 9,
                                    Language = "en",
                                    Description = "Enables the various employee functionality/access.",
                                    Name = "Employee Access",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 9,
                                    Language = "nb",
                                    Description = "Muliggjør de forskjellige funksjonalitetene og adgang for ansatte.",
                                    Name = "Ansatt brukertilgang",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 10,
                                    Language = "en",
                                    Description = "Enables the various department functionality/access.",
                                    Name = "Department Structure",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 10,
                                    Language = "nb",
                                    Description = "Muliggjør de forskjellige funksjonalitetene og adgang for avdelinger i selskapet.",
                                    Name = "Avdelings struktur",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 11,
                                    Language = "en",
                                    Description = "Enables functionality for on- and offboarding of user and customer.",
                                    Name = "Onboarding and Offboarding",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 11,
                                    Language = "nb",
                                    Description = "Muliggjør de forskjellige funksjonalitetene rund en bruker og/eller kundes oppstart eller avsluttning.",
                                    Name = "Oppstart og avluttning",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 12,
                                    Language = "en",
                                    Description = "Makes it possible for users to buy out assets.",
                                    Name = "Buyout Asset",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 12,
                                    Language = "nb",
                                    Description = "Muliggjør oppkjøp av assets for brukere.",
                                    Name = "Utkjøp av asset",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 13,
                                    Language = "en",
                                    Description = "Allows organizations to perform asset management tasks.",
                                    Name = "Asset Management",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureId = 13,
                                    Language = "nb",
                                    Description = "Lar en organisasjon utføre behandling av assets.",
                                    Name = "Asset-håndtering",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                });
                        });

                    b.Navigation("Translations");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.FeatureType", b =>
                {
                    b.OwnsMany("ProductCatalog.Infrastructure.Models.Database.FeatureTypeTranslation", "Translations", b1 =>
                        {
                            b1.Property<int>("FeatureTypeId")
                                .HasColumnType("int")
                                .HasColumnOrder(0);

                            b1.Property<string>("Language")
                                .HasMaxLength(2)
                                .IsUnicode(false)
                                .HasColumnType("char(2)")
                                .HasColumnOrder(1)
                                .IsFixedLength()
                                .HasComment("The language for this translation. This should be stored in lowercase 'ISO 639-1' format");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnOrder(3)
                                .HasComment("An optional description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnOrder(2)
                                .HasComment("A short, descriptive name");

                            b1.Property<DateTime>("PeriodEnd")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTime>("PeriodStart")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodStart");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uniqueidentifier")
                                .HasComment("The ID of the user that performed the last update.");

                            b1.HasKey("FeatureTypeId", "Language");

                            b1.ToTable("FeatureTypeTranslation");

                            b1.ToTable(tb => tb.IsTemporal(ttb =>
                                {
                                    ttb
                                        .HasPeriodStart("PeriodStart")
                                        .HasColumnName("PeriodStart");
                                    ttb
                                        .HasPeriodEnd("PeriodEnd")
                                        .HasColumnName("PeriodEnd");
                                }
                            ));

                            b1.WithOwner()
                                .HasForeignKey("FeatureTypeId");

                            b1.HasData(
                                new
                                {
                                    FeatureTypeId = 1,
                                    Language = "en",
                                    Description = "The type is not set, or is a invalid value!",
                                    Name = "Unknown",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureTypeId = 1,
                                    Language = "nb",
                                    Description = "Typen er ikke satt, eller er en ugyldig verdi!",
                                    Name = "Ukjent",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureTypeId = 2,
                                    Language = "en",
                                    Description = "This type contains functionality that enables return, recycle and other similar functionality for assets.",
                                    Name = "Asset return",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    FeatureTypeId = 2,
                                    Language = "nb",
                                    Description = "Denne typen inneholder funksjoner som muliggjør retur, resirkulering og andre lignende funksjonaliteter på assets.",
                                    Name = "Asset retur",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                });
                        });

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Joins.ProductExcludes", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Product", "RequiresProduct")
                        .WithMany("HasExcludesDependenciesFrom")
                        .HasForeignKey("ExcludesProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Product", "Product")
                        .WithMany("Excludes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RequiresProduct");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Joins.ProductFeature", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Feature", "Feature")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Product", "Product")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Joins.ProductRequiresAll", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Product", "Product")
                        .WithMany("RequiresAll")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Product", "RequiresProduct")
                        .WithMany("HasRequiresAllDependenciesFrom")
                        .HasForeignKey("RequiresProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RequiresProduct");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Joins.ProductRequiresOne", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Product", "Product")
                        .WithMany("RequiresOne")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Product", "RequiresProduct")
                        .WithMany("HasRequiresOneDependenciesFrom")
                        .HasForeignKey("RequiresProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RequiresProduct");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Order", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Product", b =>
                {
                    b.HasOne("ProductCatalog.Infrastructure.Models.Database.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ProductCatalog.Infrastructure.Models.Database.ProductTranslation", "Translations", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int")
                                .HasColumnOrder(0);

                            b1.Property<string>("Language")
                                .HasMaxLength(2)
                                .IsUnicode(false)
                                .HasColumnType("char(2)")
                                .HasColumnOrder(1)
                                .IsFixedLength()
                                .HasComment("The language for this translation. This should be stored in lowercase 'ISO 639-1' format");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnOrder(3)
                                .HasComment("An optional description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnOrder(2)
                                .HasComment("A short, descriptive name");

                            b1.Property<DateTime>("PeriodEnd")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTime>("PeriodStart")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodStart");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uniqueidentifier")
                                .HasComment("The ID of the user that performed the last update.");

                            b1.HasKey("ProductId", "Language");

                            b1.ToTable("ProductTranslation");

                            b1.ToTable(tb => tb.IsTemporal(ttb =>
                                {
                                    ttb
                                        .HasPeriodStart("PeriodStart")
                                        .HasColumnName("PeriodStart");
                                    ttb
                                        .HasPeriodEnd("PeriodEnd")
                                        .HasColumnName("PeriodEnd");
                                }
                            ));

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    ProductId = 1,
                                    Language = "en",
                                    Description = "A partner product based subscription management",
                                    Name = "Subscription management",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 1,
                                    Language = "nb",
                                    Description = "Ett partner spesifikk abonnement-håndtering produkt",
                                    Name = "Abonnement-håndtering",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 2,
                                    Language = "en",
                                    Description = "Simple Asset Management for units purchased transactionally in Techstep's own WebShop.",
                                    Name = "Implement",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 2,
                                    Language = "nb",
                                    Description = "Enkel Asset Management for enheter kjøpt transaksjonelt i Techstep egen nettbutikk.",
                                    Name = "Implement",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 3,
                                    Language = "en",
                                    Description = "Lifecycle management for transactional devices.",
                                    Name = "Transactional Device Lifecycle Management",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 3,
                                    Language = "nb",
                                    Description = "Livssyklusadministrasjon for transaksjonelle enheter",
                                    Name = "Transactional Device Lifecycle Management",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 4,
                                    Language = "en",
                                    Description = "Allow book value.",
                                    Name = "Book Value",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 4,
                                    Language = "nb",
                                    Description = "Tilgjengeliggjør bokført verdi.",
                                    Name = "Bokført verdi",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 5,
                                    Language = "en",
                                    Description = "Allows 'Recycle & Wipe' to be selected as a aftermarket option in the organizations asset-category settings.",
                                    Name = "Recycle & Wipe",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductId = 5,
                                    Language = "nb",
                                    Description = "Tilgjengeliggjør 'Recycle & Wipe' som ett alternativ inne i organisasjonens asset-kategori innstillinger.",
                                    Name = "Recycle & Wipe",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                });
                        });

                    b.Navigation("ProductType");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.ProductType", b =>
                {
                    b.OwnsMany("ProductCatalog.Infrastructure.Models.Database.ProductTypeTranslation", "Translations", b1 =>
                        {
                            b1.Property<int>("ProductTypeId")
                                .HasColumnType("int")
                                .HasColumnOrder(0);

                            b1.Property<string>("Language")
                                .HasMaxLength(2)
                                .IsUnicode(false)
                                .HasColumnType("char(2)")
                                .HasColumnOrder(1)
                                .IsFixedLength()
                                .HasComment("The language for this translation. This should be stored in lowercase 'ISO 639-1' format");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnOrder(3)
                                .HasComment("An optional description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnOrder(2)
                                .HasComment("A short, descriptive name");

                            b1.Property<DateTime>("PeriodEnd")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTime>("PeriodStart")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("PeriodStart");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uniqueidentifier")
                                .HasComment("The ID of the user that performed the last update.");

                            b1.HasKey("ProductTypeId", "Language");

                            b1.ToTable("ProductTypeTranslation");

                            b1.ToTable(tb => tb.IsTemporal(ttb =>
                                {
                                    ttb
                                        .HasPeriodStart("PeriodStart")
                                        .HasColumnName("PeriodStart");
                                    ttb
                                        .HasPeriodEnd("PeriodEnd")
                                        .HasColumnName("PeriodEnd");
                                }
                            ));

                            b1.WithOwner()
                                .HasForeignKey("ProductTypeId");

                            b1.HasData(
                                new
                                {
                                    ProductTypeId = 1,
                                    Language = "en",
                                    Description = "The type is not set, or is a invalid value!",
                                    Name = "Unknown",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductTypeId = 1,
                                    Language = "nb",
                                    Description = "Typen er ikke satt, eller er en ugyldig verdi!",
                                    Name = "Ukjent",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductTypeId = 2,
                                    Language = "en",
                                    Description = "A base-module. These types of products are stand-alone product offerings, and is typically considered a 'base' or 'core' product.",
                                    Name = "Product",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductTypeId = 2,
                                    Language = "nb",
                                    Description = "En basis-modul. Dette er frittstående produkter, og er normalt ett basis- eller kjerne-produkt.",
                                    Name = "Produkt",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductTypeId = 3,
                                    Language = "en",
                                    Description = "An option is a addon-product enables extra functionality in one or more of the modules.",
                                    Name = "Option",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                },
                                new
                                {
                                    ProductTypeId = 3,
                                    Language = "nb",
                                    Description = "En opsjon er ett tillegsprodukt som aktiverer ekstra funksjonalitet i en eller flere moduler.",
                                    Name = "Opsjon",
                                    UpdatedBy = new Guid("00000000-0000-0000-0000-000000000001")
                                });
                        });

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Feature", b =>
                {
                    b.Navigation("Excludes");

                    b.Navigation("HasExcludesDependenciesFrom");

                    b.Navigation("HasRequiresAllDependenciesFrom");

                    b.Navigation("HasRequiresOneDependenciesFrom");

                    b.Navigation("ProductFeatures");

                    b.Navigation("RequiresAll");

                    b.Navigation("RequiresOne");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.FeatureType", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.Product", b =>
                {
                    b.Navigation("Excludes");

                    b.Navigation("HasExcludesDependenciesFrom");

                    b.Navigation("HasRequiresAllDependenciesFrom");

                    b.Navigation("HasRequiresOneDependenciesFrom");

                    b.Navigation("Orders");

                    b.Navigation("ProductFeatures");

                    b.Navigation("RequiresAll");

                    b.Navigation("RequiresOne");
                });

            modelBuilder.Entity("ProductCatalog.Infrastructure.Models.Database.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
