apiVersion: v1
kind: Service
metadata:
  name: {{ include "origoapigateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "origoapigateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "origoapigateway.selectorLabels" . | nindent 4 }}