{{- if .Values.ingress.enabled -}}
{{- $fullName := include "origoassetservices.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ $fullName }}
  labels:
    app: {{ template "origoassetservices.name" . }}
    chart: {{ template "origoassetservices.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: /{{ . }}
        backend:
          serviceName: {{ $fullName | quote }}
          servicePort: {{ $servicePort }}
      {{- end }}
  {{- end }}
{{- end }}