apiVersion: v1
kind: Service
metadata:
  name: {{ include "subscriptionmanagementservices.fullname" . }}
  labels:
    {{- include "subscriptionmanagementservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "subscriptionmanagementservices.selectorLabels" . | nindent 4 }}