apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: customer-datasync-pub-sub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    secretKeyRef:
      name: rabbitmq-secrets
      key:  rabbitmq-host
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel
scopes:
  - customerservices