apiVersion: dapr.io/v1alpha1
kind: Subscription
namespace: {{ .Values.namespace }}
metadata:
  name: userAssignDepartment-subscription
spec:
  topic: user-assign-department
  route: /user-assign-department
  pubsubname: customer-pub-sub
scopes:
- customerservices
- assetservices