#apiVersion: dapr.io/v2alpha1
#kind: Subscription
#metadata:
#  name: user-assign-department-subscription
#spec:
#  pubsubname: customer-pub-sub
#  topic: user-assign-department
#  routes:
#    default: /user-assign-department
#scopes:
#  - customerservices
#  - assetservices