apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: create-department
spec:
  topic: create-department
  route: /api/v1/customer-datasync/departments/create-department
  pubsubname: customer-datasync-pub-sub
scopes:
- customerservices